add docker container for indexing bnb price #50
Octan-Labs/pipeline pull request #56
Opened 2023-07-17 02:56 UTC by dmanh1204

2023-07-17 08:42 UTC, trmaphi requested changes
Don't meet requirements

2023-07-20 09:59 UTC, trmaphi commented on dags/eth_daily_indexing_cronjob.py
> +            container_resources=k8s.V1ResourceRequirements(
cái này không cần nha

2023-07-20 09:59 UTC, trmaphi commented on dags/eth_daily_indexing_cronjob.py
> +            container_resources=k8s.V1ResourceRequirements(
test lại đi, không cần nhiều đến vậy

2023-07-20 10:30 UTC, noobmdev commented on cmc-crawl/get-cmc-historical-price-top-1000.js
> +const cryptocurrencies = require("./top1000.json").data;
I re-use Duc Manh source code :(

2023-07-20 10:31 UTC, noobmdev commented on dags/eth_daily_indexing_cronjob.py
> +            container_resources=k8s.V1ResourceRequirements(
em push nhầm đó, để bên BSC mà nhầm eth

2023-07-20 10:34 UTC, noobmdev commented on cmc-crawl/get-cmc-historical-price-top-1000.js
> +      `/historical?id=${id}&convertId=2781&timeStart=${timeStart}&timeEnd=${timeEnd}`
> what the rate limiter for the given API?

It is public API. I tried 5-10req/s

2023-07-21 07:56 UTC, trmaphi approved these changes

2023-07-21 07:56 UTC, trmaphi commented on .github/workflows/publish-to-dockerhub.yml
> +          tags: octanlabs/top-cmc-crawl:latest, octanlabs/top-cmc-crawl:${{ steps.version_info.outputs.SOURCE_TAG }}
theo cùng task luôn à?

2023-07-21 07:56 UTC, trmaphi commented on cmc-crawl/historical.Dockerfile
> +FROM node:18-alpine
Sao lại có 2 docker files ?

2023-07-21 07:56 UTC, trmaphi commented on dags/cmc_historical_price_daily_indexing_cronjob.py
> +from airflow import DAG
rồi lấy top cmc ở đâu?

2023-07-21 08:01 UTC, noobmdev commented on .github/workflows/publish-to-dockerhub.yml
> +          tags: octanlabs/top-cmc-crawl:latest, octanlabs/top-cmc-crawl:${{ steps.version_info.outputs.SOURCE_TAG }}
> theo cùng task luôn à?

vâng anh

2023-07-21 09:19 UTC, merged